

module.exports = {
    typeC: [
        "Você é a raiz quadrada de dois? Porque eu me sinto irracional ao seu redor.",
        "Você está viajando na velocidade da luz? Porque o tempo parece sempre parar quando olho para você.",
        "Você é a proteína do meu shake pós-treino, sem você não estou completo.",
        "Não sou professor de dança, mas sinto que nossos corações estão sincronizados.",
        "Juntos, nosso amor é como o melhor suplemento: potencializa nossas energias.",
        "Fique à vontade para cometer o crime de me roubar uns beijos.",
        "Aposto que você não é um meteoro, mas consegue iluminar meu mundo inteiro quando chega perto.",
        "Será que poderíamos dançar juntos? Ou até fazer mais do que isso...",
        "Me perdi no seu olhar, posso me encontrar nos seus lábios?",
        "Você deveria se colocar no seu lugar, que é em cima de mim!",
        "Gato(a), eu correria 1000KM e ficaria 2h na prancha só pra te dar um beijo. Quer mais que isso?",
        "Tem um exercício chamado “me dar um beijo” que é super eficaz para queimar calorias. Quer tentar?",
        "O treino de hoje já está pago, mas o beijo que você ia me dar ainda não!",
        "Você não é uma série de agachamentos, mas malho pensando em você o tempo todo.",
        "Será que você poderia me emprestar sua garrafinha de água? Acho que estou desidratado de tanto te admirar.",
        "Acredita em destino? Acho que fomos feitos para treinar juntos.",
        "Acho que estou fazendo exercício errado... Não paro de pular de alegria quando te vejo.",
        "Vou começar a correr por mais tempo. Preciso ficar em forma pra me encaixar certinho no seu coração!",
        "Você está fazendo mal para minha dieta fitness: não resisto a um docinho!",
        "Vou precisar fazer um detox depois do nosso encontro: você deixou meu estômago cheio de borboletas!",
        "Vou precisar me hidratar mais ainda agora que você chegou e me fez passar mal com tanta beleza!",
        "Quantos kg você levanta para aguentar carregar toda a beleza do mundo nas costas?",
        "Malhando muito para ficar forte e aguentar toda a sua areia no meu caminhãozinho!",
        "Hoje vou dobrar o tempo de cardio pro meu coração aguentar sua beleza!",
        "Ouvi dizer que hoje o clima vai esquentar, que tal começar pela gente?",
        "Quer vir em casa ver uma série? A série de beijos que vou dar em você!",
        "Não sou a previsão do tempo, mas tenho uma certeza: a temperatura vai subir quando estivermos a sós.",
        "Já te contei que virei Uber? Agora só falta você me dizer que horas eu te pego!",
        "Com você por perto, até o ar fica mais quente.",
        "Hoje quero me esquentar em você, não nos meus lençóis.",
        "Hidrogênio, que hidrogênio? Meu elemento número um é você!",
        "Você é um eixo terrestre? É porque o meu mundo gira em torno de você.",
        "Seus pais são matemáticos? Porque você é um produto notável.",
        "Meu amor por você é como a fórmula de Pi: irracional e infinito.",
        "Minha vida sem você é como um vetor nulo: não tem intensidade, direção, nem sentido.",
        "Do que adianta estudar Física, se você não respeita a lei da nossa atração?",
        "Você se chama Dopamina? Porque você consegue me deixar feliz instantaneamente.",
        "Uau! Você irradia nos comprimentos de onda mais curtos que já vi.", 
        "Meu nome é Arlindo, mas pode me chamar só de lindo, porque o ar eu perdi quando te vi.",
        "Seu nome é Google? Porque você tem as respostas para tudo o que eu procuro.",
        "Você é tão lindo(a) que, quando nasceu, a sua mãe não te deu apenas à luz, mas a companhia de energia inteira.",
        "Você não é massagem cardíaca, mas toca e reanima o meu coração.",
         "Me passa o seu Twitter? Meu pai disse que eu devo seguir o meu sonho.",
         "Você tem um band-aid? Eu ralei meu joelho caindo de amores por você.",
         "Sabe o que eu faria se fosse um gato? Passaria as minhas sete vidas com você.",
        "Eu não sou a Casas Bahia, mas prometo dedicação total a você.",
        "Nossa, quanto tempo! Lembra de mim? Ah, não… Nós só nos conhecemos dos meus sonhos.",
        "Com licença, mas você me deve uma bebida… É que derrubei a minha quando te vi.",
        "O que você fez com os meus olhos? Porque eu não consigo tirá-los de você.",
        "Você acredita em amor à primeira vista? Nem eu. Espera, deixa eu te olhar de novo.",
        "Eu e minha língua queremos saborear você sem pressa.", 
        "Me esquentando com os lençóis, mas queria mesmo era tá me esquentando com você.", 
        "As tentações como você, merecem pecados como eu.", 
        "Meu deslize favorito é o seu corpo no meu.", 
        "Dizem que fazer amor prolonga a vida, vem cá para eu te fazer imortal.", 
        "Vale massagem! Mas é como diria o filósofo, o erro é achar que para por aí.", 
        "Mais bonita que sua boca, somente ela nos meus lábios… Não disse quais.", 
        "Eu preciso conversar muito sério com você, mas tem que ser sem roupa.", 
        "Não sou de apoiar casal, mas olha eu e você, hein... Casalzão!", 
        "O que eu penso em fazer com você é um pecado, mas por isso eu aceito ir pro inferno sem reclamar.", 
        "Nada contra a sua cama, mas acho que você deveria dormir na minha.", 
        "Nosso encaixe pode ser perfeito, podemos testar isso mais tarde na minha cama.", 
        "Eu não imaginava que um cara como você poderia estar no meu caminho. É bobeira demais pedir para você ficar para sempre?",
        "Não sei você, mas eu tenho vivido minha vida como se todo dia fosse o último. Quer viver este dia comigo?",
        "Com licença, você tem um tempinho? É que eu quero me lembrar do minuto exato em que me apaixonei por você.",
        "Oi, eu só queria agradecer pelo presente. Estou usando esse sorriso desde que você me deu.",
        "Se eu ganhasse 5 reais toda vez que eu visse alguém bonito com você, eu teria ganho só 5 reais.",
        "Se amor fosse preto e carinho fosse branco, o que eu sinto por você seria xadrezinho.",
        "Um toque seu é o suficiente para a gente começar a realizar todos os meus desejos mais intensos…", 
        "Quero cuidar do meu namorado para ele não ficar doente nunca… É só chá por cima de chá.", 
        "Hoje eu queria cometer um crime, roubar uns beijos teus. O que vem depois ainda ainda é segredo.", 
        "Ouvi dizer que hoje o clima esquenta, sabe dizer se é verdade e se topa me ajudar nisso?", 
        "Estou tão cansada hoje que só queria sentar em você.", 
        "Basta um toque seu em meu corpo para que todos meus desejos com você comecem a se tornar a minha realidade.", 
        "Sua boca valeu o preço de perder todo o sossego que eu tinha.", 
        "Você gostaria de passar a noite vendo estrelas? Conheço um motel que tem 5.", 
        "Eu, você, Netflix, uma cama e um dia chuvoso. Bora? 💭", 
        "Sabe o que te deixaria mais e feliz e também ficaria bem em você?  Eu.", 
        "Quer fazer um teste para os bombeiros apagando meu fogo hoje?", 
        "Acho que eu e você nos encaixamos perfeitamente, se é que você me entende.", 
        "Tô aqui chupando uma bala mas poderia ser você, topa?", 
        "Tentação é quando a mente proíbe e o corpo desobedece, posso te mostrar na prática.", 
        "E aí, rola suas pernas aquecendo minhas orelhas?", 
        "Sobre você, eu não diria que tenho uma mente suja, mas uma imaginação quente.", 
        "Vale replay: já que na primeira vez foi bom, esse ticket é um convite para repetir os beijos.", 
        "Só me confirma seu nome mesmo... É que eu preciso saber o que é que eu vou gritar hoje à noite.", 
        "Andei te observando e percebi que você tem todos os pré-requisitos para vir tirar a minha roupa… topa?", 
        "Quando eu abrir seu zíper, vai ser como as portas do paraíso se abrindo para nós dois. Topa?", 
        "Que cor de roupa preciso usar na virada de ano pra você vir tirar?",
        "Não sou o Papai Noel, mas poderia te proporcionar uma noite feliz... ",
        "Meu Deus, estou sem ar, me ajuda! Acho que você precisa fazer respiração boca-boca para me salvar... ",
        "Acredita em amor à primeira vista, ou devo passar por você de novo?",
        "Deve haver algo errado com meus olhos. Eu não posso tirá-los de você.", 
        "Se você fosse uma música, você seria aquela que não sai da minha cabeça",
        "Você não é a Monalisa, mas é uma obra de arte.",
        "Se as estrelas fossem tão lindas como você, eu passaria as noites em claro.",
        "Se as estrelas fossem tão lindas como você, eu passaria as noites em claro.",
        "Meu coração sempre capota na curva do seu sorriso.",
        "Você é a primeira maravilha do meu mundo.",
        "Sabe com qual signo o meu combina? Com o seu!",
        "Me chama de tabela periódica e diz que está rolando uma química entre nós.",
        "Você não é o Death Note, mas atingiu meu coração em 40 segundos.",
        "Tá vendo aquele cara ali? Pois é, ele tá perguntando se você quer ficar comigo.",
        "Me empresta uma foto sua para eu mostrar para o Papai Noel o que quero de presente!"
        ,"Vamos ao cartório para eu passar o meu coração para o seu nome.",
        "Aposto um beijo que você vai me dar um fora.", 
        "Suas pernas não doem de fugir dos meus sonhos todas as noites, meu amor?", 
        "Me chame de urna eletrônica e me dê seu voto de confiança."
    ],
    typeF: [
        "O cérebro humano é formado por, aproximadamente, 75% de água.",
        "O cachorro-quente é uma invenção alemã do século XV.",
        "Alguns animais, como os cangurus, não param de crescer mesmo atingindo a idade adulta.",
        "A maioria das vacas não consegue descer escadas.",
        "Em média, um adulto respira 550 litros de oxigênio puro diariamente.",
        "Estima-se que 4% da população mundial seja canhota.", 
        "A maior palavra da língua portuguesa refere-se a uma doença causada pela respiração de cinzas vulcânicas: pneumoultramicroscopicossilicovulcanoconiótico.",
        "O Brasil é o país que possui a maior comunidade japonesa fora do Japão. Só em São Paulo, moram mais de 600 mil japoneses.",
        "O calendário da Etiópia é sete anos atrasado em relação aos demais países do ocidente.",
        "A avenida mais larga do mundo, com 14 faixas diferentes, fica na Argentina.",
        "Mais de 10% de toda a biodiversidade do mundo é encontrada no continente australiano.",
        "A Rússia é o maior país do mundo, ocupando cerca de 10% de toda a terra do planeta.",
        "Na Holanda, estima-se que o número de bicicletas ultrapasse três vezes o número de veículos.",
        "O menor país do mundo é o Vaticano, com cerca de 800 habitantes oficiais.",
        "Mais de 10% de toda a biodiversidade do mundo é encontrada no continente australiano.",
        "A Rússia é o maior país do mundo, ocupando cerca de 10% de toda a terra do planeta.",
        "Na Holanda, estima-se que o número de bicicletas ultrapasse três vezes o número de veículos.",
        "O menor país do mundo é o Vaticano, com cerca de 800 habitantes oficiais.",
        "O Sol converte cerca de 600 milhões de toneladas de hidrogênio em hélio a cada segundo em virtude do processo de fusão nuclear.",
        "Um volume do tamanho da cabeça de um alfinete feito do material de uma estrela de nêutrons teria uma massa de 1 milhão de toneladas.",
        "A parte mais profunda do oceano chega a 11 mil metros.",
        "O esqueleto humano é formado por 206 ossos, no entanto, os bebês nascem com cerca de 270 ossos, que se fundem em ossos maiores.",
        "A Terra orbita o Sol a uma velocidade de, aproximadamente, 107 mil km/h.",
        "O corpo humano tem mais de 96 mil km de vasos sanguíneos.",
        "Estima-se que o Universo conte com mais de 10 bilhões de galáxias.",
        "A luz do Sol leva cerca de 8 minutos e 20 segundos para chegar à Terra.",
        "O dia tem, aproximadamente, 23 horas e 56 minutos, não 24 horas. Por isso, a cada quatro anos, adicionamos um dia ao mês de fevereiro. Esses anos são chamados de bissextos.",
        "O recorde de voo de uma galinha é de 13 segundos.",
        "Os mosquitos são os animais mais letais do mundo, causando mais mortes humanas do que todas as guerras da história. Esses seres vivos matam cerca de 725 mil humanos anualmente.",
        "Uma pulga pode saltar até 350 vezes sua altura.",
        "As formigas são capazes de levantar até 50 vezes seu próprio peso.",
        "Todos os mamíferos são capazes de saltar, menos os elefantes.",
        "Girafas não têm cordas vocais.",
        "A língua de uma baleia-azul pode pesar até 3,6 toneladas, o equivalente ao peso de um elefante médio.",
        "As borboletas têm cerca de 12 mil olhos.",
        "Os vertebrados mais longevos do mundo são os tubarões da Groenlândia, que podem viver cerca de 400 anos.",
        "Existem algumas árvores vivas espalhadas pelo mundo que têm, pelo menos, 5000 anos de idade.",
        "Os ursos-polares são, praticamente, invisíveis pelas câmeras de calor em virtude da eficiente camada de gordura isolante que os protege do frio.",
        "A palavra “brasil” significa “vermelho como brasa”.",
        "O Brasil é o maior produtor de café do mundo.",
        "O Brasil é também o país que mais desmata a natureza em todo o mundo.",
        "O Brasil tem a maior biodiversidade do mundo graças à Floresta Amazônica.",
        "Das 30 cidades mais violentas do mundo, 12 estão localizadas no Brasil.",
        "Toda moeda circulante e oficial do Brasil é produzida na Casa da Moeda, no Rio de Janeiro.",
        "Tocantins é o estado mais novo do Brasil, fundado em 1988.",
        "A feijoada é considerada o prato nacional do Brasil.",
        "O verbo “testemunhar” é baseado nos tribunais romanos onde os homens juravam pelos testículos sobre alguma declaração.",
        "O pintor Vincent Van Gogh vendeu apenas uma pintura quando ainda estava vivo: Red Vineyard at Arles.",
        "Uma cobra píton grande o suficiente, é capaz de engolir uma cabra inteira, ou coisas piores...",        
        "A primeira forma de escrita conhecida pela humanidade foi a escrita cuneiforme, desenvolvida pelos sumérios, na Mesopotâmia.",
        "Os primeiros europeus a pisarem na América foram os vikings, que chegaram no Canadá por volta do ano 1000.",
        "Quando D. Pedro I anunciou a independência do Brasil, em 7 de setembro de 1822, ele sofria de problemas intestinais causados por consumo de água ou comida contaminada.",
        "Vidkun Quisling foi um norueguês que colaborou para que seu país fosse invadido pela Alemanha durante a Segunda Guerra Mundial. O termo quisling entrou para o dicionário inglês como sinônimo de traidor.",
        "Estima-se que cerca de 35 mil brasileiros tenham falecido entre 1918 e 1919 por conta da gripe espanhola.",
        "Carlos Luz foi o presidente do Brasil que menos tempo ficou no cargo. O mandato dele durou apenas três dias.",
        "Os moais são construções megalíticas construídas pelos rapa nui na Ilha de Páscoa, e o moai mais pesado tem cerca de 75 toneladas.",
        "A primeira cidade fundada pelos portugueses no Brasil foi a cidade de São Vicente, em 1532.", 
        "Os povos celtas ficaram assim conhecidos porque os gregos deram-lhes o nome genérico de “keltoi”.",
        "O monarca absolutista com o reinado mais longo foi Luís XIV, possuindo um reinado de 72 anos de duração.",
        "Fundada em julho de 1994, pelo engenheiro e ex-CEO Jeff Bezos, a Amazon foi inicialmente registrada como Cadabra.Inc. A ideia era fazer uma referência à palavra mágica “Abracadabra”. No entanto, quando o primeiro advogado de Bezos leu o nome pela primeira vez, alertou o empresário de que a associação não soava tão clara assim. Além disso, algumas pessoas confundiam o nome com a palavra “cadáver”.",
        "Chamado de “WorldWideWeb”, o primeiro navegador da história foi criado em 1990 por Tim Berners-Lee, cientista de computação britânico.",
        "O primeiro spam foi enviado há 44 anos, em 1978. A mensagem em massa foi disparada por Gary Thuerk, gerente de marketing da ARPANET, para promover um novo modelo de computador. Cerca de 400 clientes potenciais receberam a mensagem. Apesar de ter arrecadado US$ 13 milhões (cerca de R$ 69,7 milhões em conversão direta) em vendas, a empresa também recebeu muitas ligações de pessoas reclamando dos e-mails indesejados.",
        "Estima-se que, a cada ano, o monte Everest cresça 4 milímetros.",
        "A cada minuto, cerca de 72 horas de conteúdo são enviados ao site de vídeos Youtube.",
        "A barragem da maior usina hidrelétrica do mundo, a Usina das Três Gargantas, localizada na China, prolongaria a duração do dia em 0,66 microssegundos se operasse em sua capacidade máxima. Isso ocorreria em virtude da enorme massa de água que ela comporta.",
        "Durante o fenômeno Superlua, calcula-se que o diâmetro lunar possa aumentar em até 14%.",
        "Há uma lâmpada que permanece ligada continuamente há mais de 113 anos na cidade de Livermore, na Califórnia.",
        "O Oceano Pacífico tem uma profundidade média de 4.267 metros.",
        "“640 Kb -de memória- devem ser suficientes para qualquer um” ... Bill Gates em 1981.",
        "“MINOLTA” vem das siglas em inglês para “Machinery and INstruments OpticaL de Kazuo TAshima (fundador da empresa de câmeras nipo-alemã). A primeira câmera da marca Minolta foi introduzida no mercado em 1932.”",
        "“Não gostamos de como eles soam, e a música de guitarra está saindo de moda”, disse a Decca Recording Company em 1962, quando rejeitou os Beatles.",
        "“O Poderoso Chefão” (o Poderoso Chefão) foi uma adaptação cinematográfica do romance de Mario Puzo sobre a Máfia. No filme de 1972, Marlon Brando era o chefe da Máfia, apelidado de “o Poderoso Chefão”. As pessoas presumem que “Padrinho” é uma palavra que a multidão realmente usou. Na verdade, e segundo Puzo, o termo “padrinho” foi inventado por ele mesmo ... nadi usou o termo “padrinho” (ou “padrinho”) para se referir aos criminosos, nem mesmo na máfia. No entanto, as notícias começaram a ser vistas imediatamente depois, e é relatado que ainda hoje é usado no mundo do crime.",
        "“SANYO” significa “três oceanos” em japonês. Toshio Iue, que fundou a empresa em 1947, planejava vender para todo o mundo, nos oceanos Atlântico, Pacífico e Índico.",
        "10 gramas de cafeína ou 100 xícaras de café tomadas em 4 horas podem matar um ser humano.",
        "10% das receitas da Rússia vêm da venda de Vodka.",
        "10% dos ossos de um gato estão presentes em sua cauda.",
        "110.000 pessoas tinham mais de 100 anos em 2004.",
        "12% dos americanos pesquisados ​​acreditavam que Joana d'Arc (Joana d'Arc em inglês) era a esposa de Noé, aquele com a arca.",
        "15% das mulheres americanas mandam flores para si mesmas no dia dos namorados.",
        "16% das mulheres nascem loiras e 33% das mulheres são loiras.",
        "2.800 pizzas seriam necessárias para formar uma torre da altura da Torre de Pisa.",
        "20% do metano na atmosfera se deve às emissões de gases produzidos por insetos e animais domésticos (como vacas e baratas) e esse metano é responsável por boa parte do efeito estufa que causa o aquecimento global do nosso planeta.",
        "226 soldados morreram em 1850 quando atravessavam uma ponte na França. Enquanto eles marchavam, causaram uma ressonância (vibração) muito grande na ponte, levando esta se partir. Desde então, as tropas são proibidas de marchar nas pontes",
        "31.557.600.000 segundos equivalem a um Milênio.",
        "33% da população não consegue estalar os dedos.", 
        "360.000 é o número de vagas disponíveis no exército suíço, cujos profissionais são apenas 3.300.",
        "Um homem gasta em média 145 dias da sua vida se barbeando",
        "4 asteroides se chamam “Beatles”.",
        "4% da riqueza mundial é o suficiente para amenizar as necessidades básicas do mundo.",
        "40% das pessoas que se mudam também mudam de marca de creme dental ao mesmo tempo.",
        "45% dos Americanos não sabem que o Sol é uma estrela.",
        "7% dos americanos acredita que Elvis está vivo. 25% dos americanos acha que Sherlock Holmes existiu. 25% também acreditam em fantasmas, e 10% dizem ter visto um.",
        "7% dos americanos comem diariamente no McDonald’s.",
        "70% do corpo humano é composto de água.",
        "90% de um iceberg flutuante está submerso.",
        "Einstein nunca foi um bom aluno, e nem sequer falava direito aos 9 anos. Seus pais achavam que ele era retardado.",
        "O Oceano Atlântico é mais salgado que o Pacífico.",
        "A “nota azul” é uma nota musical que dá a uma música um toque de blues.", 
        "A American Airlines economizou $ 40.000 em 1987 ao eliminar uma azeitona de cada salada servida em primeiro lugar. classe.",
        "A American Airlines fez uma economia de $40,000 em 1987 eliminando uma azeitona de cada salada servida na primeira classe.",
        "A Anatidaefobia é o medo que um pato esteja observando você",
        "A Antártida é o único continente que não tem nenhuma zona terrestre abaixo do nível do mar.",
        "A Antártida é o único continente sem répteis.",
        "A Austrália é o sexto maior país (em área) do Mundo com 7.682.300 quilômetros quadrados. Possui 36.375 quilômetros de litoral. A população Australiana é estimada em 25 milhões de habitantes, o que significa apenas 3 habitantes por quilometro quadrado.",
        "A Avenida 9 de Julho, maior do mundo, na Argentina",
        "A BBC London (British Broadcasting Corporation) ficou profundamente angustiada quando descobriu que eles pagavam extras brancos até cinco vezes mais do que extras negros durante uma filmagem na África de uma série de documentários intitulada “The Luta contra a escravidão”.",
        "A Barbie já vendeu mais carros que a General Motors. Ela é também a boneca mais bem sucedida da história dos brinquedos. Alguns colecionadores possuem até 7000 bonecas.",
        "A Basílica de São Pedro pode acomodar 50.000 pessoas, um pouco menos do que o Yankee Stadium, com 57.545 lugares.",
        "A CIA tentou espionar a embaixada russa e o Kremlin na década de 1960. Usaram gatos como ferramenta de escuta, implantando microfones nos animais.",
        "A China faz fronteira com 16 países diferentes.",
        "A Cidade do México, Distrito Federal, tem o maior número de táxis do mundo, com mais de 60.000.",
        "A Cidade do Vaticano, sede da Igreja Católica Romana, em Roma, é o menor país do mundo, medindo 0,16 milhas quadradas. Menos da metade do tamanho do próximo menor país, Mônaco, com 0,4 milhas quadradas. A Cidade do Vaticano se tornou um país independente em 1929. Seus 750 habitantes são governados pelo Papa e por um comitê de três cardeais.",
        "A Coca Cola era originalmente verde.",
        "A Coca-Cola foi inventada em Atlanta, Georgia nos EUA pelo Dr. John S. Pemberton em 1886; a Pepsi Cola foi inventada por Caleb Bradham 12 anos mais tarde.",
        "A Coca-Cola seria verde se não fossem adicionados corantes",
        "A Disney World, na Florida abriu ao público em 1O parque de diversões era o maior do mundo. Custou 400 milhões de Euros e durante o primeiro ano o número de visitantes não foi o esperado. Apenas 10.000 pessoas visitaram o parque nesse ano. Hoje em dia, o parque recebe 10.000 visitantes por dia.", 
        "A Dra. June A. Carroll, de Indio, Califórnia, nos Estados Unidos morava em um trecho particularmente perigoso da estrada e, em 1912, ela pintou uma linha cerca de um quilômetro no meio da estrada para ajudar os motoristas a permanecerem do lado direito. fora da estrada. A California Highway Commission gostou tanto da ideia que pintou linhas no meio de todas as estradas pavimentadas do estado. Assim nasceram as divisões das estradas.",
        "A Fundação de Eletricidade da Austrália do Sul é dona da menor propriedade de que se tem notícia no mundo: um tiquinho de terra, de forma quadrada, que mede 24 milímetros de lado. A propriedade está registrada em cartórios, mas até agora ninguém descobriu o que se pode fazer com ela.",
        "A Irlanda tem um santuário de burros, onde são mantidos burros velhos que foram retirados de circulação. O último relatório indica que existem 120.",
        "A Islândia consome mais Coca Cola per capita do que qualquer outro país do mundo.",
        "A Itália importa a maior parte de sua massa dos Estados Unidos e Canadá.",
        "A Nintendo já possuiu uma companhia de taxi",
        "A Rainha Elizabeth I é creditada como a pessoa que inventou o guarda-roupa, já que ela mandou construir uma sala especial com um gancho para pendurar todas as roupas que tinha, e tinha milhares.",
        "A Rússia é o maior país do mundo, ocupando cerca de 10% de todo o planeta.",
        "A Santa Sé, também conhecida como Vaticano, é a menor nação independente do mundo, ocupando aproximadamente 108 acres no centro de Roma. Tem seu próprio exército, jornal e correio.",
        "A Shell Oil Company era anteriormente uma loja de novidades em Londres chamada The Shell Shop. Em meados de 1800, o proprietário, Marcus Samuel, tinha muito sucesso vendendo caixas de conchas. Importar conchas também lhe rendeu dinheiro e seus negócios de importação e exportação realmente se expandiram quando ele percebeu que também poderia exportar querosene. A empresa Shell Shop tornou-se a Shell Transport and Trading Company e, eventualmente, a Shell Oil Company.",
        "A Terra fica 0,02 graus mais quente durante a lua cheia.",
        "A Terra fica 100 kg mais pesada todo dia devido a queda de pó espacial",
        "A Terra possui um campo magnético extremamente poderoso, nos protegendo de ventos solares.",
        "A Terra viaja a uma velocidade de 66.641 milhas por hora em torno de nosso sol.",
        "A Torre Eiffel, localizada em Paris, é o monumento mais visitado do mundo, recebendo cerca de seis milhões de turistas por ano. Apelidada carinhosamente de Dama de Ferro pelo povo francês, a torre de 324 metros de altura pesa 10.100 toneladas distribuídas em três andares. O monumento, construído por Gostai Eiffel, foi inaugurado em 31 de março de 1889 como a principal atração da Exposição Universal de Paris. Nessa época, era considerada a mais alta construção do mundo e sustentava no topo uma bandeira francesa de doze metros.",
        "A Torre de Hércules, nos arredores de La Coruña, na Espanha, tem 185 pés de altura e é o farol mais antigo ainda em uso. Data do reinado do imperador romano Trajano entre os anos 98 a 117 depois de Cristo.",
        "A URSS, ou União das Repúblicas Socialistas Soviéticas, é composta por 15 repúblicas: Armênia, Azerbaijão, Bielo-Rússia, Estônia, Geórgia, Cazaquistão, Quirguizia, Letônia, Lituânia, Moldávia, República Socialista Soviética Federada Russa, Tajiquistão, Turmenistão, Ucrânia, Uzbequistão.",
        "A acupuntura foi usada pela primeira vez como um tratamento médico no ano 2700 antes de Cristo pelo Imperador Chinês Shen-Nung.",
        "A arca de Noé media 450 x 75 x 45 pés. Como você sabe? A Bíblia diz que tinha 300 por 50 por 30 côvados e, de acordo com Gênesis 6:15, um côvado equivale a 18 polegadas.",
        "A atividade cerebral é tão única quanto as impressões digitais, podendo agir de forma exclusiva em cada indivíduo.",
        "A atriz de cinema mudo de Hollywood Norma Talmadge (1897-1957) iniciou a tradição de registrar suas pegadas no Grauman Chinese Theatre na cidade de Hollywood, no estado da Califórnia, nos Estados Unidos, quando acidentalmente tropeçou em concreto fresco em o banco em frente ao teatro em 1927.",
        "A baleia assassina é na verdade um golfinho",
        "A bandeira americana com 56 estrelas, foi projetada por um aluno de Ohio, que tinha apenas 17 anos. A professora ainda deu nota baixa para o trabalho.",
        "A bandeira do Reino Unido é apropriadamente conhecida como “a Union Flag” e só é chamada de Union Jack como é comumente conhecida, quando é hasteada de um navio.",
        "A barata tem dois cérebros, um na cabeça e um menor na cauda.",
        "A barba mais longa media 1.83 metros e pertencia ao indiano Shamsher Singh. A medida foi feita desde o queixo até à ponta da barba, em 18 de Agosto de 1997.",
        "A biblioteca da Universidade de Indiana afunda 2 cm por ano porque, quando foi construída, os engenheiros esqueceram-se de incluir o peso dos livros no cálculo das fundações.",
        "A biblioteca da Universidade de Indiana afunda mais de 1 polegada por ano porque, ao projetar o prédio, eles se esqueceram de calcular para o peso do prédio, quanto pesariam os livros.",
        "A borboleta monarca, em seu estado larval, alimenta-se de uma planta venenosa, por isso os pássaros não as comem, pois essas borboletas são tóxicas.",
        "A cabeça da girafa fica a mais de dois metros de distância do coração. Para fazer o sangue subir, o coração precisa ser muito forte. O coração da girafa é 43 vezes maior que o do ser humano.",
        "A cada 45 segundos, uma casa é queimada nos Estados Unidos (pobre casa!)",
        "A cada ano, 98% dos átomos do nosso corpo são substituídos.",
        "A cada ano, mais pessoas morrem por picadas de abelha do que por tubarões.",
        "A cada minuto, cerca de 72 horas de conteúdo são enviadas para o site de vídeos do YouTube.",
        "A cada segundo, aproximadamente 3 crianças nascem no mundo.",
        "A cadeira elétrica foi inventada por um dentista.",
        "A caneta esferográfica da marca BIC leva o nome do Barão Biche que não inventou a esferográfica, mas foi o húngaro Lászó Biró em 1938. A empresa francesa BIC de Baron Biche, comprou a empresa inglesa que concordou em produzir as canetas. Na Inglaterra a caneta ainda é conhecida como “biro”, na França como “bic”.",
        "A categoria “mensagens inúteis” domina os textos publicados no serviço de microblog Twitter, segundo a empresa de pesquisa Pear Analytic. Em um recente estudo, a companhia divulgou que esse tipo de mensagem (pointless babble, em inglês) responde por 40,55% de todas aquelas publicadas no site. Para chegar a essa conclusão, foram analisados 2 mil twitts escritos em inglês, durante duas semanas.",
        "A causa número um da depressão entre pessoas casadas: ser casado.",
        "A causa número um da depressão entre pessoas solteiras: ser solteiro.",
        "A chita (a chita) é o único felino do mundo que não consegue retrair suas garras.",
        "A cidade com mais Rolls Royce per capita é Hong Kong.",
        "A comida do pato não causa eco.",
        "A coroação da rainha Elizabeth II foi marcada para o dia 2 de junho de 1953, em parte porque os meteorologistas diziam que, no ano inteiro, esse era o dia com mais probabilidades de ser ensolarado. Mas choveu…",
        "A crise está afetando as relações amorosas. Pesquisa feita nos EUA com adúlteros revelou que apenas 32% dos homens vão manter seus gastos com amantes – todos os demais vão cortar custos. Já as mulheres não querem nem saber: 54% delas vão manter ou até aumentar o gasto com amantes. Vai ver esse dinheiro venha de seus maridos.",
        "A crosta terrestre tem cerca de 35 quilômetros de espessura.",
        "A dança aeróbica causa mais fraturas ósseas do que qualquer outra atividade recreativa.",
        "A decomposição humana começa apenas 4 minutos após a morte.",
        "A distância entre os olhos de um crocodilo, em centímetros, é diretamente proporcional a todo o seu comprimento em pés.",
        "A doença conhecida mais antiga do mundo é a lepra, cujos primeiros registros datam de 1350 a.C.. Apesar da idade, um tratamento rápido e eficaz contra ela só foi descoberto no início dos anos 80, com o desenvolvimento da quimioterapia. A moléstia é causada pela bactéria Mycrobacterium Leprae, e ataca principalmente os nervos e a pele, podendo causar deformações em estágios mais avançados. Devido ao preconceito com o qual a doença é encarada, o seu nome foi mudado em alguns países para hanseníase.",
        "A duração de um ano é de 365 dias mais um quarto de dia. O acúmulo dessas frações acabou trazendo na época de Júlio César, no Império Romano, uma alteração notável entre as datas vulgares e as revoluções celestes. O famoso astrônomo alexandrino, Sosigenes, foi chamado por Júlio César a Roma para resolver essa diferença. Sosigenes propôs que o ano comum continuasse a ser 365 dias e que a cada quatro anos um dia fosse adicionado para torná-lo.",
        "A dureza relativa dos minerais em uma escala de 1 a 10 é chamada de escala de Mohs. O diamante mede 10 Mohs. O talco mede 1 Mohs.",
        "A esposa de Claudius I tentou envenenar seu marido com cogumelos venenosos em 54 DC. O médico de Cláudio tentou fazê-lo vomitar fazendo cócegas em sua garganta com uma pena de pássaro. Claudio engasgou com a caneta e morreu.",
        "A estrela do mar é um dos únicos animais que podem virar o estômago para fora.",
        "A estátua erguida em Viena em memória do compositor Franz Schubert consistia em mais do que ele jamais ganhou com seu trabalho.",
        "A explosão de uma estrela é chamada de Supernova e estima-se que pode gerar uma energia de 10.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000 ergs. Para efeito de comparação, a primeira bomba atômica produziu 1.000.000.000.000.000.000.000 de ergs de energia.",
        "A expressão “barreira do som” nasceu da idéia (errada) de que a velocidade do som era o limite da velocidade de vôo de um avião. Esta idéia mudou completamente quando o primeiro avião atingiu uma velocidade “supersônica” (acima da barreira do som). A primeira vez que se atravessou a barreira do som foi no dia 13 de Fevereiro de 1Quem o fez foi um piloto de ensaios de nome Chuck Yeagen, no avião foguete Bell X-1.",
        "A fenda que temos acima do lábio superior é chamada de filtro.",
        "A filha de Shakespear era analfabeta.",
        "A folha de alumínio é feita de blocos sólidos de alumínio. O bloco é alisado com um rolo até se tornar uma folha fina. Para finalizar, duas camadas de folha de alumínio são passadas ao mesmo tempo por um rolo de aço polido. As faces que estiveram em contato com o rolo são brilhantes, enquanto as internas ficam com acabamento fosco.",
        "A formiga cai sempre para o seu lado direito quando é intoxicada.",
        "A força necessária para dar três espirros consecutivos, queima exatamente o mesmo numero de calorias que um 0rgasmo.",
        "A frase “A rápida raposa marrom salta sobre o cão preguiçoso” usa todas as letras do alfabeto inglês. (Desenvolvido pela Western Union para testar comunicações telex / twx).",
        "A frase ”regra dos dedos” vem de uma antiga lei britânica que dizia que não se pode bater em uma esposa com nada mais largo que um dedo.",
        "A gazela, um antílope africano, não bebe água. Para sobreviver, ele extrai a umidade necessária dos alimentos que ingere.",
        "A gema do ovo de avestruz é a maior célula única do mundo.",
        "A girafa pode limpar seus ouvidos com sua língua de 21 polegadas.",
        "A girafa é o único animal que nasce com chifres, embora ao nascer os traga esmagados contra a cabeça, mas em uma semana eles brotam.",
        "A guerra mais curta da história foi entre Zanzibar e Inglaterra em 1O zanzibar rendeu-se ao fim de 38 minutos.",
        "A idade da nossa Lua é de aproximadamente 4,72 bilhões de anos.",
        "A ideia de fazer a barba surgiu quando Alexandre, o Grande, ordenou que seus soldados raspassem a barba para que os soldados do exército inimigo não pudessem agarrá-los em combate.",
        "A ilha de Nauru, no Pacífico, baseia sua economia quase inteiramente nas fezes de pássaros.",
        "A lagosta carnívora, que habita nas águas costeiras da Austrália, conta-se entre os predadores mais rápidos da Terra. Este crustáceo marinho captura com as pinças as suas presas, geralmente outras lagostas, em apenas cinco milisegundos.",
        "A lei de Kentucky, nos Estados Unidos, exige que todas as pessoas no estado tomem banho pelo menos uma vez por ano.",
        "A lei do estado da Califórnia nos Estados Unidos proíbe dormir na cozinha ... mas permite cozinhar no quarto.",
        "A letra “J” não aparece em nenhuma parte da tabela periódica dos elementos.",
        "A letra Q é a única letra do alfabeto que não aparece em nenhum dos nomes dos Estados Unidos.",
        "A letra mais antiga do alfabeto é a letra “o”, usada pela primeira vez pelos egípcios cerca de 3.000 anos antes de Cristo. As últimas letras são “j” e “v”. A consoante “j” não foi distinguida da vogal “i” até 1600, não até a Renascença que a consoante “v” foi distinguida da vogal “u”.",
        "A letra ou texto do hino nacional japonês data do século IX, mas a música foi composta em 1880.",
        "A lula gigante tem os maiores olhos de qualquer ser vivo do mundo.",
        "A língua de um baleia-azul pode pesar até 3,6 toneladas, ou o equivalente ao peso de um elefante médio.",
        "A língua de uma baleia azul pesa tanto quanto um elefante adulto.",
        "A língua do camaleão tem o dobro do comprimento do corpo.",
        "A maior e a mais bela igreja do mundo é a Basílica de São Pedro, no Vaticano. Ocupa área de 15 mil metros quadrados e tem capacidade para 60 mil fiéis. Em frente da Basílica, está a Praça de São Pedro, de forma ovalada, com 280 metros de comprimento máximo e 280 metros de largura na sua zona mais larga.",
        "A maior escultura do mundo é a de Jefferson Davis, Robert E. Lee e Thomas “Stonewall” Jackson, que cobre 1,33 acre na face da Stone Mountain perto de Atlanta, Geórgia, nos Estados Unidos. Foi criado entre 12 de setembro de 1963 e 3 de março de 1972.",
        "A maior goiabada do mundo pesava 550 quilos.",
        "A maior obra-prima da pintura de todos os tempos, Mona Lisa, de Leonardo da Vinci, foi um dos primeiros retratos da história da arte ocidental a incluir as mãos do modelo. Até então, os retratos mostravam as mulheres apenas do busto para cima.",
        "A maior árvore documentada foi um eucalipto australiano, que em 1872 tinha pouco mais de 130 metros de altura.",
        "A maioria das partículas de poeira nas casas são feitas de pele morta.",
        "A maioria dos animais e plantas adaptam-se ao meio que os rodeia. Os castores fazem exatamente o contrário, eles alteram o ambiente de acordo com as suas necessidades. Constroem lagos e barragens para proteger as suas tocas que têm entradas subaquáticas.",
        "A maioria dos batons contêm escamas de peixe.",
        "A maioria dos egípcios que dirigem seus carros à noite não está acostumada a acender as luzes. Aparentemente, as luzes vistas no Cairo pertencem a carros dirigidos por estranhos e turistas.",
        "A maioria dos mamíferos vê as cores apenas em tons de cinza. Primatas como macacos, gorilas, etc. eles podem perceber todo o espectro de cores. Também alguns peixes e pássaros.",
        "A maioria dos mamíferos vê cores apenas em tons de cinza. Primatas como macacos, gorilas, etc. eles podem perceber todo o espectro de cores. Também alguns peixes e pássaros.",
        "A maioria dos peixes não dorme, embora tenham períodos marcados de atividade reduzida. Alguns peixes dormem em recifes de coral apoiados em rochas ou em pé na cauda.",
        "A maioria dos relâmpagos tem um comprimento médio de 3 a 5 Km e têm uma corrente de 10.000 ampéres a 100 milhões de volts.",
        "A mais antiga edificação da Antártica, uma cabana construída pelo explorador Carsten Borchgrevnik em 1899, está literalmente soterrada por pilhas de excremento de pingüins.",
        "A mais longa avenida do mundo, com 14 faixas diferentes, localizada na Argentina.",
        "A mais longa corrida até hoje realizada no mundo foi a transcontinental, de Nova York a Luz Angeles, em 1O finlandês Johnny Calo venceu o percurso de 5.898 quilômetros em 79 dias (525h 57min 20seg), de 31 de março a 18 de junho. Chegou com apenas 2 min 47 à frente do inglês Pietro “Peter” Gavuzzi.",
        "A maneira mais fácil de diferenciar um animal carnívoro de um herbívoro é olhando para os seus olhos. Os carnívoros (cães, leões) possuem os olhos na parte da frente da cabeça, o que facilita a localização do alimento. Já os herbívoros (aves, coelhos) possuem os olhos do lado da cabeça para perceber a aproximação de um possível predador.",
        "A medição da força dos tornados é baseada na quantidade de destruição que eles deixam em seu rastro e foi desenvolvida pelo Professor Ted Fujita e é chamada de Escala de Intensidade de Tornado Fujita e vai de F1 a F6 com F1 sendo classificado como fraco, F2 e F3 tão forte, F4 e F5 tão violento. Um tornado F6 ainda não foi documentado, mas estima-se que o vento pode atingir velocidades de 320 a 380 milhas por hora. Um F6 também é conhecido como um “tornado inconcebível”",
        "A medição de “uma liga” pode variar entre 2,4 e 4,6 milhas.",
        "A melodia de piano “Chopsticks” foi supostamente escrita como um exercício de piano por Arthur de Lulli em 1877. O nome é um pseudônimo de uma garota de dezesseis anos chamada Eupemia Allen.",
        "A microfatografia inventada no início dos anos 1920 era uma máquina criada para enviar segredos durante os períodos de guerra. Sua extraordinária tecnologia permitiu a inscrição de mais de 4.000 palavras em uma superfície do tamanho de um grão de arroz.",
        "A mãe de MElanie Griffith é a atriz Tippi Hendren, mais conhecida por seu papel principal no filme “Os Pássaros”, de Alfred Hitchcock.",
        "A mão humana tem 27 ossos e 35 músculos.",
        "A música que foi tocada enquanto o presidente Bush subia ao pódio em uma convenção republicana em Houston em 1992, depois que o discurso de sua esposa sobre os valores da família foi extraído do musical homossexual “La Cage Aux Folles”.",
        "A navalha de ouro encontrada na tumba do rei Tutancâmon era afiada o suficiente para ser usada.",
        "A noz-moscada é extremamente venenosa se for injetada nas veias.",
        "A palavra “Caribe” vem da mesma raiz que “canibal”.",
        "A palavra “astronauta” se origina das palavras gregas astron, que quer dizer estrela, e nautes, que quer dizer marinheiro.",
        "A palavra “brasil” significa “vermelho like ember”.",
        "A palavra “cientista” foi usada pela primeira vez em 1833. Até lá eram chamados apenas de filósofos ou ”homens da ciência”.",
        "A palavra “piranha” vem da língua tupi da América do Sul e significa “dente de peixe”. Em alguns dialetos locais da região amazônica, o nome de um tipo de tesoura artesanal também é “piranha”.",
        "A palavra “refrigerante” é derivada de um de seus componentes que é usado para produzir bolhas: o sódio.",
        "A palavra “salário” evoluiu de “salarium argentium” ou “dinheiro do sal”, pagamentos que os soldados romanos recebiam para comprar suas coisas.",
        "A palavra “sizígia” é usada pelos astrônomos para descrever a posição de três corpos que estão aproximadamente alinhados. Por exemplo, quando há lua cheia, ela está em sizígia com a Terra e o Sol, porque está na parte mais distante do Sol da Terra.",
        "A palavra “sótão” vem da Ática, na Grécia antiga. Lá, um sótão era uma espécie de andar baixo acima do andar principal. No entanto, ao longo dos séculos, a palavra “sótão” passou a se referir a qualquer espaço baixo acima do último andar de um edifício.",
        "A palavra em inglês “crap” significa algo como “merda” em espanhol e é derivada do primeiro banheiro que usava água para esvaziar seu conteúdo, e foi desenvolvido em 1837. O nome deste primeiro banheiro desse tipo era “Crapper's Valveless Water Waste Preventor” ou em espanhol “Crapper's Valveless Water Waste Preventor”, em homenagem ao seu inventor, o engenheiro sanitário inglês Thomas Crapper.",
        "A palavra mais longa em espanhol é 'inconstitucionalmente', seguida do nome do músculo do pescoço 'esternocleidomastóideo'.",
        "A palavra portuguesa “bom”, que significa “agradável”, deriva da palavra latina “nescius”, ou “ignorante”, que vem de “descire” ou “não saber”. Nos séculos XIV e XV, a frase “uma pessoa boa” significava “uma pessoa boa”, naquela época conotada “idiota” ao invés de “agradável”. No entanto, com o passar dos anos, “bom” tornou-se uma conotação mais favorável, mas suave.",
        "A palavra proibida em árabe é harém.",
        "A palavra árabe usada para representar uma quantidade desconhecida era 'shei'. Isso foi transcrito para o grego como 'xei'. Por fim, foi encurtado e deixado apenas como 'x'. Portanto, x é qualquer número.",
        "A parte de metal que suporta a sombra de um abajur é chamada de “harpa”.",
        "A pelagem do urso polar não é branca, já que os seus pelos são transparentes. Parecem brancos porque têm pequenas bolhas de ar para o seu isolamento térmico, que dispersam a luz.",
        "A pele de uma rã venenosa dourada, possui toxinas suficientes para matar 100 pessoas!"
    ],
    get cantadas() {
        return this.typeC[Math.floor(Math.random() * this.typeC.length)];
    },
    get fatos() {
        return this.typeF[Math.floor(Math.random() * this.typeF.length)];
    }
};
